function Disclaimer() {
    return (
        <div className="bg-white py-24 sm:py-32">
            <div className="mx-auto max-w-8xl px-6 lg:px-8">
                <div className="mx-auto max-w-3xl text-center">
                    <p className="mt-2 text-3xl font-bold tracking-tight text-gray-700 sm:text-4xl">Disclaimer</p>
                    <p className="mt-6 text-md leading-8 text-gray-600">
                        The Sapphire/Ruby Appraisal Calculator is designed to provide users with an estimated value of gemstones based on the inputs provided. Please note the following:
                        <ul className="mt-6 text-base leading-8 text-gray-600 list-disc text-justify">
                            <li>No Authenticity Verification: This tool does not detect or verify the authenticity of gemstones (e.g., whether they are real or synthetic). We recommend consulting a certified gemologist for verification.                            </li>
                            <li>Estimated Values Only: The appraisal values generated by the calculator are based on an AI model trained on general gemstone data. These values are approximate and may not reflect the true market value of your gemstone.                            </li>
                            <li>No Guarantee of Accuracy: While we strive for accuracy, the model may occasionally produce inaccurate or non-representative results due to limitations in data or the provided inputs.                            </li>
                            <li>Use at Your Own Risk: This calculator is a supplementary tool and should not replace professional appraisal or expert advice. By using this tool, you acknowledge and accept these limitations.                            </li>
                            <li>Privacy and Security: We value your privacy and will not share your data with any third parties without your consent.</li>
                        </ul>
For precise and certified appraisals, we encourage you to consult a licensed gemologist or gemstone valuation expert. 
                    </p>
                </div>
            </div>
        </div>
    );
}

export default Disclaimer